import Resbtn from '../assets/resbtn.svg';
import Land from '../assets/land.svg';
import Ring from '../assets/ring.svg';
import Ring1 from '../assets/ring1.svg';
import snow from '../assets/snow.svg';
import Metamask from '../assets/metamask.svg';
import Decoration1 from '../assets/decoration1.svg';
import underline from '../assets/underline.svg';
import shine from '../assets/shine.svg';
import direct from '../assets/direct.svg';

export const ResbtnImg = Resbtn;
export const LandImg = Land;
export const RingImg = Ring;
export const SnowImg = snow;
export const Ring1Img = Ring1;
export const MetamaskImg = Metamask;
export const Decoration1Img = Decoration1;
export const UnderlineImg = underline;
export const ShineImg = shine;
export const DirectImg = direct;